baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sebastian Sciarra" #title of website
theme = ["basic", "hugo-cite"]#use basic theme

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding = false
# Set to "hide" or "show" all codes by default
codefolding_show = "show"
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton = true

pygmentsUseClasses = true
pygmentsCodefences = true #allows .Rmd code fences to be used and properly converted
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "about\\.html", "static/blog/\\*_files/", "README"]

[params]
  author = "Sebastian Sciarra"
  description = "Seb's portfolio site"
  gh_url = "https://api.github.com/users"
  gh_user = "sciarraseb"
  technical = "technical_post_summ"
  coding =  "coding_summ"
  simulation =  "simulation_summ"
  resources =  "ml_resources"


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true




